language: cpp
sudo: required
dist: wily
compiler:
- clang
os:
- osx
#- linux

ruby: 2.2.0

before_install:
- echo $CC
- echo $CXX
#- yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/linuxbrew/go/install)"
#- export PATH="$PATH:/$HOME/.linuxbrew/bin"
- brew update
- brew install qt5
- brew link --force qt5
- brew install qbs
- export QBS_SETTINGS_DIR=$HOME/config

before_script:
- qmake -query
- qbs-setup-toolchains --detect
- qbs-setup-qt /usr/local/opt/qt5/bin/qmake qt5
- qbs-config profiles.qt5.baseProfile clang
- qbs-config defaultProfile qt5

script: qbs install project.with_webkit:false

branches:
  only:
  - master
