language: cpp
sudo: required
dist: wily
compiler:
- clang
os:
- linux

before_install:
- echo $CC
- echo $CXX
- export QBS_SETTINGS_DIR=$HOME/config
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt update; sudo apt install qbs qtdeclarative5-dev; fi

before_script:
- qbs-setup-toolchains --detect
- qbs-config profiles.qt5.baseProfile clang
- qbs-config defaultProfile qt5

script: qbs install

branches:
  only:
  - master
