language: cpp
sudo: required
dist: wily
compiler:
- clang
os:
- linux

addons:
  apt:
    packages:
      - qtdeclarative5-dev 
      - qtbase5-dev

before_install:
- echo $CC
- echo $CXX
- export QBS_SETTINGS_DIR=$HOME/config
- sudo apt-get install qbs

before_script:
- qbs-setup-toolchains --detect
- qbs-config profiles.qt5.baseProfile clang
- qbs-config defaultProfile qt5

script: qbs install

branches:
  only:
  - master
