language: cpp
sudo: required
dist: wily
compiler:
- clang
os:
- linux

before_install:
- echo $CC
- echo $CXX
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
- sudo apt-get install qt5-default qttools5-dev-tools
- sudo apt-get install qbs
- export QBS_SETTINGS_DIR=$HOME/config

before_script:
- qbs-setup-toolchains --detect
- qbs-config profiles.qt5.baseProfile clang
- qbs-config defaultProfile qt5

script: qbs install

branches:
  only:
  - master
