os: Visual Studio 2015

environment:
  matrix:
  # MSVC x86
  - name: win32
    platform: amd64_x86
    qt: 5.6\msvc2015
    suffix: msvc2015

  # MSVC x64
  - name: win64
    platform: amd64
    qt: 5.6\msvc2015_64
    suffix: msvc2015

  # MinGW
  - name: win32
    platform: mingw
    qt: 5.6\mingw49_32
    suffix: mingw

init:
  - if %platform%==mingw set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %platform%==mingw set PATH=C:\Qt\Tools\mingw492_32\bin;%PATH%
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - set QTDIR=C:\Qt\%qt%
  - if not %platform%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%
  - if not %platform%==mingw (set makefiles="NMake Makefiles") else (set makefiles="MinGW Makefiles")
  - if %APPVEYOR_REPO_TAG%==true (set nogitinfo=ON) else (set nogitinfo=OFF)

install:
  - cinst qbs

build_script:
  - qbs-setup-toolchains --detect
  - qbs-setup-qt %QTDIR%\bin\qmake.exe qt5
  - qbs config defaultProfile qt5
  - qbs install project.with_webkit:false

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
